server:
  port: 8001


spring:
  application:
    name: cloud-payment-service
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 106.15.187.41:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6o64b5z8mo3875ako.mysql.rds.aliyuncs.com:3306/mytest?useSSL=false
    username: root
    password: Mysql_root_1995

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.springcloud.entities

logging:
  level:
    root: info
    org.springframework: info