server:
  port: ${port:56010}


spring:
  application:
    name: quickstart-provider
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 106.15.187.41:8848
logging:
  level:
    root: info
    org.springframework: info